name: Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: false
      - name: Configure RubyGems credentials (OIDC)
        uses: rubygems/configure-rubygems-credentials@v1.0.0
      - name: Build gem
        run: gem build *.gemspec
      - name: Push gem
        run: gem push *.gem
